# Generated by Django 5.0.6 on 2024-06-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='learning_type',
            field=models.CharField(choices=[('Visual Learner', 'Visual Learner'), ('Auditory Learner', 'Auditory Learner'), ('Kinesthetic Learner', 'Kinesthetic Learner'), ('Communicative Learner', 'Communicative Learner')], max_length=50),
        ),
    ]
